module.exports = {
    purge: ["./src/**/*.{js,jsx,ts,tsx}"],
    darkMode: false, // or 'media' or 'class'
    theme: {
        colors: {
            transparent: "transparent",
            black: "#000",
            white: "#F4FFFF",
            cyan: {
                light: "#92ddce",
                DEFAULT: "#4ec9b0",
            },
            pink: {
                DEFAULT: "#EF60ED",
            },
            purple: "#BD80FF",
            orange: "#FF9367",
            grey: {
                darker: "#212529",
                dark: "#343a40",
                DEFAULT: "#495057",
                light: "#6c757d",
                lighter: "#adb5bd",
            },
        },
        fontFamily: {
            body: ["Open Sans"],
        },
        spacing: {
            default: "20px",
            xxs: "2px",
            xs: "5px",
            s: "10px",
            m: "20px",
            l: "40px",
            xl: "80px",
        },
        fontSize: {
            xxs: ".8em",
            xs: ".95em",
            s: "1.1em",
            m: "1.35em",
            l: "1.8em",
            xl: "2em",
            xxl: "2.4em",
            xxxl: "4.5em",
        },
        lineHeight: {
            xs: "1.1",
            s: "1.2",
            m: "1.3",
            l: "1.4",
            xl: "1.5",
            xxl: "1.6",
            reset: "1",
        },
        fontWeight: {
            standard: 400,
            bold: 600,
            bolder: 800,
        },
        screens: {
            tablet: "640px",
            laptop: "1024px",
            desktop: "1280px",
            wide: "1536px",
        },
        scale: {
            0: "0",
            25: ".25",
            50: ".5",
            75: ".75",
            90: ".9",
            95: ".95",
            100: "1",
            101: "1.01",
            105: "1.05",
            110: "1.1",
            125: "1.25",
            150: "1.5",
            200: "2",
            250: "2.5",
        },
    },
    variants: {
        extend: {},
    },
    plugins: [],
};
